import { expect, test } from "@playwright/test";
import { monitorBrowserErrors } from "./fixtures/browser-errors";
import { decodeRgbaPng, expectPng, readDownload } from "./fixtures/downloads";
import { publicationSegyUpload } from "./fixtures/seismic-fixtures";

test("@smoke renders a portrait publication grayscale section with page margins, contrast, and an immutable viewport", async ({ page }, testInfo) => {
  const assertBrowserErrors = monitorBrowserErrors(page); await page.goto("/"); await page.getByTestId("segy-file-input").setInputFiles(publicationSegyUpload); await expect(page.getByTestId("dataset-name")).toContainText("100 traces"); const beforeMode = await page.getByTestId("seismic-plot").getAttribute("data-mode");
  await page.getByTestId("plot-png").click(); const dialog = page.getByRole("dialog"); await dialog.locator("#png-target").selectOption("publication-section"); await dialog.locator("#png-preset").selectOption("custom"); await dialog.locator("#png-width").fill("800"); await dialog.locator("#png-height").fill("1600"); await dialog.locator("#png-background").selectOption("#ffffff"); await dialog.locator("#section-time-start").fill("0"); await dialog.locator("#section-time-end").fill("10"); await dialog.locator("#section-title-1").fill("4: 50–160 Hz"); await dialog.locator("#section-title-2").fill("10 s"); await dialog.locator("#section-x-label").fill("Receiver"); await dialog.locator("#section-filename").fill("publication-section-reference-test.png");
  const downloadPromise = page.waitForEvent("download"); await dialog.getByRole("button", { name: "Export PNG" }).click(); const download = await downloadPromise; expect(download.suggestedFilename()).toBe("publication-section-reference-test.png"); await expectPng(download, 800, 1600); const bytes = await readDownload(download); if (testInfo.project.name === "chromium") expect(bytes).toMatchSnapshot("publication-section-reference-test.png"); const png = decodeRgbaPng(bytes); let dark = 0; let light = 0; let medium = 0;
  for (let offset = 0; offset < png.pixels.length; offset += 4) { const value = png.pixels[offset] ?? 0; if (value < 28) dark += 1; if (value > 245) light += 1; if (value >= 118 && value <= 138) medium += 1; }
  expect(dark).toBeGreaterThan(500); expect(light).toBeGreaterThan(10_000); expect(medium).toBeGreaterThan(10_000); expect(png.pixels[800 * 4] ?? 0).toBeGreaterThan(245); await dialog.getByRole("button", { name: "Close" }).click(); await expect(page.getByTestId("seismic-plot")).toHaveAttribute("data-mode", beforeMode ?? "wiggle"); assertBrowserErrors();
});
