import { describe, expect, it } from "vitest";
import { BlobOutputSink } from "../../src/io/sink/output-sink";
import { SegyReader } from "../../src/io/segy/segy-reader";
import { SegyWriter } from "../../src/io/segy/segy-writer";
import { HeaderScalars } from "../../src/io/segy/headers/header-scalars";
import { MemorySource, makeSegy } from "../fixtures/segy-fixture";

describe("SegyReader", () => {
  it("opens ASCII IEEE variable-length traces lazily", async () => { const source = new MemorySource(makeSegy({ traces: [{ samples: [1, 2, 3] }, { samples: [4, 5], sampleIntervalMicroseconds: 2000 }], extendedHeaders: ["C01 EXTENDED HEADER"] })); const dataset = await SegyReader.open(source); expect(dataset.traceCount).toBe(2); expect(dataset.textualHeaders).toHaveLength(2); expect(dataset.traceIndex.sampleCounts).toEqual(new Uint32Array([3, 2])); expect(dataset.traceIndex.sampleIntervalsMicroseconds).toEqual(new Uint32Array([1000, 2000])); expect(source.requests[0]).toEqual({ offset: 0, length: 3600 }); expect(await dataset.traces.readTrace(1)).toEqual(new Float32Array([4, 5])); expect(Math.max(...source.requests.map((item) => item.length))).toBeLessThanOrEqual(3600); });
  it("opens EBCDIC IBM and non-standard little endian fixtures", async () => { const ibm = await SegyReader.open(new MemorySource(makeSegy({ formatCode: 1, encoding: "ebcdic", revision: 0, traces: [{ samples: [1, -2, 16] }] }))); expect(ibm.textualHeaders[0]?.encoding).toBe("ebcdic"); expect(await ibm.traces.readTrace(0)).toEqual(new Float32Array([1, -2, 16])); const little = await SegyReader.open(new MemorySource(makeSegy({ littleEndian: true, traces: [{ samples: [2.5] }] }))); expect(little.littleEndian).toBe(true); expect((await little.traces.readTrace(0))[0] ?? 0).toBe(2.5); });
  it("opens a revision 2 later numeric format", async () => { const dataset = await SegyReader.open(new MemorySource(makeSegy({ revision: 2, formatCode: 15, traces: [{ samples: [0, 16_777_215] }] }))); expect(dataset.binaryHeader.values.revision).toBe(2); expect(await dataset.traces.readTrace(0)).toEqual(new Float32Array([0, 16_777_215])); });
  it("round trips every byte with no edits, including raw unknown header regions", async () => { const bytes = makeSegy({ traces: [{ samples: [1, 2], fieldRecordNumber: 17, sourceX: 100, receiverX: 125 }], extendedHeaders: ["C01 EXTRA"] }); const view = new Uint8Array(bytes); view[3200 + 399] = 0xab; view[6800 + 239] = 0xcd; const dataset = await SegyReader.open(new MemorySource(bytes)); const sink = new BlobOutputSink(); await SegyWriter.write(dataset, sink); expect(new Uint8Array(await sink.toBlob().arrayBuffer())).toEqual(new Uint8Array(bytes)); });
  it("writes explicit header edits without discarding unknown bytes", async () => { const bytes = makeSegy({ traces: [{ samples: [1, 2], fieldRecordNumber: 17 }] }); new Uint8Array(bytes)[3600 + 239] = 0xab; const dataset = await SegyReader.open(new MemorySource(bytes)); const sink = new BlobOutputSink(); await SegyWriter.write(dataset, sink, { traceHeaderEdits: [{ traceId: 0, fieldId: "fieldRecordNumber", value: 99 }] }); const output = await sink.toBlob().arrayBuffer(); const roundTrip = await SegyReader.open(new MemorySource(output)); expect((await roundTrip.traces.readHeader(0)).raw("fieldRecordNumber")).toBe(99); expect(new Uint8Array(output)[3600 + 239] ?? 0).toBe(0xab); });
  it("re-encodes samples when an export changes numeric format or byte order", async () => { const dataset = await SegyReader.open(new MemorySource(makeSegy({ traces: [{ samples: [1.25, -2.5] }] }))); const sink = new BlobOutputSink(); await SegyWriter.write(dataset, sink, { sampleFormatCode: 3, endianness: "little" }); const converted = await SegyReader.open(new MemorySource(await sink.toBlob().arrayBuffer())); expect(converted.littleEndian).toBe(true); expect(converted.binaryHeader.values.sampleFormatCode).toBe(3); expect(await converted.traces.readTrace(0)).toEqual(new Float32Array([1, -3])); });
  it("indexes revision 2 trace-header extensions without decoding them", async () => { const source = new MemorySource(makeSegy({ revision: 2, traces: [{ samples: [1, 2], traceHeaderExtensionCount: 1 }, { samples: [3] }] })); const dataset = await SegyReader.open(source); expect(dataset.traceIndex.headerExtensionBytes).toEqual(new Uint32Array([240, 0])); expect(await dataset.traces.readTrace(1)).toEqual(new Float32Array([3])); });
  it("writes streaming subsets without copying unselected traces", async () => { const dataset = await SegyReader.open(new MemorySource(makeSegy({ traces: [{ samples: [1] }, { samples: [2, 3] }] }))); const sink = new BlobOutputSink(); await SegyWriter.write(dataset, sink, { traceIds: new Uint32Array([1]) }); const subset = await SegyReader.open(new MemorySource(await sink.toBlob().arrayBuffer())); expect(subset.traceCount).toBe(1); expect(await subset.traces.readTrace(0)).toEqual(new Float32Array([2, 3])); });
  it("recognizes count-until-EndText extended headers", async () => { const bytes = makeSegy({ extendedHeaders: ["C01 ((SEG: ENDTEXT))"], traces: [{ samples: [1] }] }); new DataView(bytes).setInt16(3504, -1, false); const dataset = await SegyReader.open(new MemorySource(bytes)); expect(dataset.textualHeaders).toHaveLength(2); });
  it("applies coordinate and elevation scalars without changing raw values", async () => { const dataset = await SegyReader.open(new MemorySource(makeSegy({ traces: [{ samples: [1], sourceX: 12345, coordinateScalar: -100, elevationScalar: 10 }] }))); const header = await dataset.traces.readHeader(0); expect(header.raw("sourceX")).toBe(12345); expect(header.scaled("sourceX")).toBe(123.45); expect(HeaderScalars.apply(12, 0)).toBe(12); expect(HeaderScalars.apply(12, -10)).toBe(1.2); });
  it("reports truncated trailing trace data with byte context", async () => { const complete = makeSegy({ traces: [{ samples: [1, 2] }, { samples: [3, 4] }] }); const truncated = complete.slice(0, complete.byteLength - 3); const dataset = await SegyReader.open(new MemorySource(truncated)); expect(dataset.traceCount).toBe(1); expect(dataset.diagnostics.some((issue) => issue.code === "TRUNCATED_TRACE_DATA" && issue.byteOffset === 3848)).toBe(true); });
  it("reports unknown sample format", async () => { const bytes = makeSegy({ traces: [{ samples: [1] }] }); new DataView(bytes).setUint16(3224, 14, false); await expect(SegyReader.open(new MemorySource(bytes))).rejects.toThrow(/sample format/i); });
});
