import type { TraceBlock } from "../../core/model/trace";
import { throwIfAborted } from "../../core/errors/errors";
import type { ProcessingContext, ProcessingInputMetadata, ResourceEstimate, SeismicProcessor, ValidationIssue } from "../api/processor";
export interface ResamplingParameters { readonly targetSampleIntervalSeconds: number; readonly halfKernelSamples?: number; }
/** Windowed-sinc arbitrary-rate resampler. Its cutoff prevents aliasing before decimation. */
export class ResamplingProcessor implements SeismicProcessor<ResamplingParameters> {
  public readonly id = "resample"; public readonly version = "1.0.0"; public readonly displayName = "Resample";
  public validate(_input: ProcessingInputMetadata, parameters: ResamplingParameters): readonly ValidationIssue[] { return parameters.targetSampleIntervalSeconds > 0 ? [] : [{ severity: "error", field: "targetSampleIntervalSeconds", message: "Target sample interval must be positive seconds." }]; }
  public estimateResources(input: ProcessingInputMetadata, parameters: ResamplingParameters): ResourceEstimate { const factor = input.sampleIntervalSeconds / parameters.targetSampleIntervalSeconds; return { peakBytes: Math.ceil(input.maximumSamplesPerTrace * Math.max(1, factor) * 8), operations: input.traceCount * input.maximumSamplesPerTrace * (parameters.halfKernelSamples ?? 16) * 2, workerRecommended: true }; }
  public async processBlock(block: TraceBlock, parameters: ResamplingParameters, context: ProcessingContext): Promise<TraceBlock> { const all: Float32Array[] = []; let total = 0; for (let row = 0; row < block.traceIds.length; row += 1) { throwIfAborted(context.signal, "Resampling"); const start = block.sampleOffsets[row] ?? 0; const end = block.sampleOffsets[row + 1] ?? start; const out = this.resample(block.samples.subarray(start, end), block.sampleIntervalSeconds, parameters.targetSampleIntervalSeconds, parameters.halfKernelSamples ?? 16); all.push(out); total += out.length; context.reportProgress(row + 1, block.traceIds.length); } if (total > 0xffffffff) throw new RangeError("Resampled TraceBlock exceeds Uint32 offsets; split input batch."); const offsets = new Uint32Array(all.length + 1); const samples = new Float32Array(total); let cursor = 0; for (let index = 0; index < all.length; index += 1) { offsets[index] = cursor; const trace = all[index] ?? new Float32Array(0); samples.set(trace, cursor); cursor += trace.length; } offsets[all.length] = cursor; await Promise.resolve(); return { ...block, sampleOffsets: offsets, samples, sampleIntervalSeconds: parameters.targetSampleIntervalSeconds }; }
  public resample(input: Float32Array, sourceDt: number, targetDt: number, halfKernel: number): Float32Array { if (!(sourceDt > 0) || !(targetDt > 0) || !Number.isInteger(halfKernel) || halfKernel < 1) throw new RangeError("Resampling requires positive sample intervals and an integer kernel half-width."); if (input.length === 0) return new Float32Array(0); if (sourceDt === targetDt) return input.slice(); const count = Math.max(1, Math.floor((input.length - 1) * sourceDt / targetDt) + 1); const output = new Float32Array(count); const ratio = targetDt / sourceDt; const cutoff = 0.5 * Math.min(1, 1 / ratio); for (let index = 0; index < count; index += 1) { const position = index * ratio; if (position === 0) { output[index] = input[0] ?? 0; continue; } const center = Math.floor(position); let sum = 0; let weights = 0; for (let tap = -halfKernel; tap <= halfKernel; tap += 1) { const inputIndex = center + tap; if (inputIndex < 0 || inputIndex >= input.length) continue; const delta = inputIndex - position; const ideal = delta === 0 ? 2 * cutoff : Math.sin(2 * Math.PI * cutoff * delta) / (Math.PI * delta); const window = 0.5 + 0.5 * Math.cos(Math.PI * delta / (halfKernel + 1)); const weight = ideal * window; sum += (input[inputIndex] ?? 0) * weight; weights += weight; } output[index] = Math.abs(weights) > Number.EPSILON ? sum / weights : 0; } return output; }
}
