import { MapExportRenderer } from "../../export/png";
import { downloadBlob } from "../../export/download";
import { GeometryBuilder, GeometryQcAnalyzer } from "../../geometry";
import type { SegyDataset } from "../../io/segy";
import { GeometryMapRenderer, MapSpatialIndex, fitViewport, panViewport, screenToWorld, zoomViewportAt } from "../../visualization/map";

export interface GeometryMapPanelOptions { readonly onSelectTrace: (traceId: number) => void; }

/** Lightweight offline geometry/QC panel with pan, wheel zoom, hit testing, linked selection, and PNG export. */
export class GeometryMapPanel {
  public constructor(private readonly options: GeometryMapPanelOptions) {}
  public async open(dataset: SegyDataset): Promise<void> {
    const table = await GeometryBuilder.fromSegy(dataset); const bounds = table.bounds(); if (!bounds) throw new Error("No finite coordinates are available for the geometry map."); const qc = GeometryQcAnalyzer.analyze(table); const dialog = document.createElement("dialog"); dialog.innerHTML = `<form method="dialog" class="panel"><h2>Offline geometry map and coordinate QC</h2><p id="geometry-note"></p><canvas id="geometry-map" width="900" height="540" aria-label="Offline geometry map"></canvas><pre id="geometry-qc"></pre><menu><button id="geometry-png" type="button">Export PNG</button><button value="cancel">Close</button></menu></form>`; document.body.append(dialog); dialog.addEventListener("close", () => dialog.remove()); dialog.showModal();
    const canvas = this.byId<HTMLCanvasElement>(dialog, "geometry-map"); const note = this.byId<HTMLElement>(dialog, "geometry-note"); const qcText = this.byId<HTMLElement>(dialog, "geometry-qc"); const context = canvas.getContext("2d"); if (!context) throw new Error("Geometry map canvas is unavailable."); let viewport = fitViewport(bounds, canvas.width, canvas.height); const renderer = new GeometryMapRenderer(); const spatial = new MapSpatialIndex(table); const selected = new Set<number>(); const findings = new Set<number>(qc.findings.flatMap((item) => Array.from(item.traceIds)));
    const render = (): void => renderer.render(context, table, viewport, { width: canvas.width, height: canvas.height, selectedTraceIds: selected, findingTraceIds: findings }); render(); note.textContent = `${qc.summary.sourceCount} source positions, ${qc.summary.receiverCount} receiver positions. Coordinates remain local; no tiles or reprojection are used.`; qcText.textContent = qc.findings.map((finding) => `[${finding.severity}] ${finding.code}: ${finding.message}`).join("\n") || "No coordinate-QC findings.";
    let drag: { readonly x: number; readonly y: number } | undefined; canvas.addEventListener("pointerdown", (event) => { drag = { x: event.offsetX, y: event.offsetY }; canvas.setPointerCapture(event.pointerId); }); canvas.addEventListener("pointermove", (event) => { if (!drag || event.buttons === 0) return; viewport = panViewport(viewport, event.offsetX - drag.x, event.offsetY - drag.y); drag = { x: event.offsetX, y: event.offsetY }; render(); }); canvas.addEventListener("pointerup", (event) => { if (!drag) return; const movement = Math.hypot(event.offsetX - drag.x, event.offsetY - drag.y); drag = undefined; if (movement > 3) return; const world = screenToWorld({ x: event.offsetX, y: event.offsetY }, viewport, canvas.width, canvas.height); const hit = spatial.hitTest(world.x, world.y, viewport, canvas.width, canvas.height); if (hit) { selected.clear(); selected.add(hit.traceId); this.options.onSelectTrace(hit.traceId); render(); } }); canvas.addEventListener("wheel", (event) => { event.preventDefault(); viewport = zoomViewportAt(viewport, { x: event.offsetX, y: event.offsetY }, event.deltaY < 0 ? 1.25 : 0.8, canvas.width, canvas.height); render(); }, { passive: false });
    this.byId<HTMLButtonElement>(dialog, "geometry-png").addEventListener("click", () => void MapExportRenderer.export(table, { width: canvas.width, height: canvas.height, viewport, selectedTraceIds: selected, findingTraceIds: findings }).then((blob) => downloadBlob(blob, "geometry-map.png")));
  }
  private byId<T extends HTMLElement>(root: ParentNode, id: string): T { const value = root.querySelector<T>(`#${id}`); if (!value) throw new Error(`Missing geometry panel element #${id}.`); return value; }
}
