import { defaultSampleCodecRegistry } from "../../src/io/segy/codecs/sample-codec-registry";
import { TextualHeader, type TextualEncoding } from "../../src/io/segy/headers/textual-header";
import type { RandomAccessSource } from "../../src/io/source/random-access-source";

export interface FixtureTrace {
  readonly samples: readonly number[];
  readonly fieldRecordNumber?: number;
  readonly traceIdCode?: number;
  readonly sourceX?: number;
  readonly receiverX?: number;
  readonly coordinateScalar?: number;
  readonly elevationScalar?: number;
  readonly sampleIntervalMicroseconds?: number;
  readonly traceHeaderExtensionCount?: number;
}
export interface FixtureOptions { readonly formatCode?: number; readonly littleEndian?: boolean; readonly encoding?: TextualEncoding; readonly extendedHeaders?: readonly string[]; readonly sampleIntervalMicroseconds?: number; readonly revision?: 0 | 1 | 2; readonly traces: readonly FixtureTrace[]; }

export function makeSegy(options: FixtureOptions): ArrayBuffer {
  const formatCode = options.formatCode ?? 5; const codec = defaultSampleCodecRegistry.get(formatCode); const littleEndian = options.littleEndian ?? false; const dt = options.sampleIntervalMicroseconds ?? 1000; const encoding = options.encoding ?? "ascii"; const extended = options.extendedHeaders ?? []; const ns = options.traces[0]?.samples.length ?? 0;
  const traceBytes = options.traces.reduce((total, trace) => total + 240 + (trace.traceHeaderExtensionCount ?? 0) * 240 + trace.samples.length * codec.bytesPerSample, 0); const output = new ArrayBuffer(3600 + extended.length * 3200 + traceBytes); const bytes = new Uint8Array(output); const header = new TextualHeader(new Uint8Array(3200), encoding).withCards(["C01 SYNTHETIC SEG-Y TEST FIXTURE", "C02 GENERATED BY VITEST"], encoding); bytes.set(header.rawBytes, 0);
  for (let index = 0; index < extended.length; index += 1) bytes.set(new TextualHeader(new Uint8Array(3200), encoding).withCards([extended[index] ?? ""], encoding).rawBytes, 3600 + index * 3200);
  const binary = new DataView(output, 3200, 400); binary.setUint16(16, dt, littleEndian); binary.setUint16(20, ns, littleEndian); binary.setUint16(24, formatCode, littleEndian); binary.setUint16(300, (options.revision ?? 1) << 8, littleEndian); binary.setUint16(302, 0, littleEndian); binary.setInt16(304, extended.length, littleEndian);
  let offset = 3600 + extended.length * 3200;
  for (let index = 0; index < options.traces.length; index += 1) {
    const trace = options.traces[index] ?? { samples: [] }; const extensionCount = trace.traceHeaderExtensionCount ?? 0; const traceDt = trace.sampleIntervalMicroseconds ?? dt; const headerBytes = 240 + extensionCount * 240; const view = new DataView(output, offset, headerBytes + trace.samples.length * codec.bytesPerSample); view.setInt32(0, index + 1, littleEndian); view.setInt32(4, index + 1, littleEndian); view.setInt32(8, trace.fieldRecordNumber ?? 1, littleEndian); view.setInt16(28, trace.traceIdCode ?? 1, littleEndian); view.setInt16(68, trace.elevationScalar ?? 1, littleEndian); view.setInt16(70, trace.coordinateScalar ?? 1, littleEndian); view.setInt32(72, trace.sourceX ?? 0, littleEndian); view.setInt32(80, trace.receiverX ?? 0, littleEndian); view.setInt16(88, 1, littleEndian); view.setUint16(114, trace.samples.length, littleEndian); view.setUint16(116, traceDt, littleEndian); if ((options.revision ?? 1) === 2) view.setUint16(232, extensionCount, littleEndian); const samples = Float32Array.from(trace.samples); codec.encode?.(samples, 0, samples.length, view, headerBytes, littleEndian); offset += headerBytes + samples.length * codec.bytesPerSample;
  }
  return output;
}

export class MemorySource implements RandomAccessSource {
  public readonly requests: { offset: number; length: number }[] = [];
  public readonly size: number;
  public constructor(public readonly bytes: ArrayBuffer, public readonly name = "fixture.segy") { this.size = bytes.byteLength; }
  public async read(offset: number, length: number, signal?: AbortSignal): Promise<ArrayBuffer> { if (signal?.aborted) throw signal.reason ?? new DOMException("Aborted", "AbortError"); this.requests.push({ offset, length }); if (offset < 0 || length < 0 || offset + length > this.size) throw new RangeError("out of bounds"); await Promise.resolve(); return this.bytes.slice(offset, offset + length); }
}
