import { SegyReader, type SegyDataset, TraceHeaderSchema } from "../io/segy";
import { openLegacySegdViewer } from "../io/segd/legacy-compatibility";
import { SmartSoloConversionDialog } from "../ui/dialogs/smartsolo-conversion-dialog";
import { GeometryMapPanel } from "../ui/panels/geometry-map-panel";
import { CsvExportDialog } from "../ui/dialogs/csv-export-dialog";
import { PngExportDialog } from "../ui/dialogs/png-export-dialog";
import { SweepCorrelationDialog } from "../ui/dialogs/sweep-correlation-dialog";
import { CorrelationPlan } from "../processing/vibroseis/correlation";
import { SweepDetector } from "../sweep/sweep-detector";
import { SweepExtractor } from "../sweep/sweep-extractor";
import { WiggleRenderer, type WiggleView } from "../visualization/wiggle-renderer";
import { appStyles } from "../ui/styles";
import { initialLocalRuntimeStatus, localServerRuntimeStatus } from "./local-runtime-status";

type RightTab = "text" | "binary" | "trace" | "qc";
interface DatasetEntry { readonly dataset: SegyDataset; }

/** DOM controller owns UI state; file I/O and DSP are accessed solely through public modules. */
export class AppController {
  private readonly entries: DatasetEntry[] = [];
  private activeIndex = -1;
  private selectedTrace = 0;
  private currentTab: RightTab = "text";
  private renderer: WiggleRenderer | undefined;
  private view: WiggleView = { firstTrace: 0, traceCount: 32, timeStartSeconds: 0, timeEndSeconds: 1, mode: "wiggle", gain: 1, clip: 2 };

  public constructor(private readonly root: HTMLElement) {}
  public mount(): void { this.root.innerHTML = `<style>${appStyles}</style><div class="app"><header class="toolbar"><span class="brand">SEISMIC PROCESSING TOOLKIT</span><span id="dataset-chip" data-testid="dataset-name" class="meta">No local data loaded</span><span class="spacer"></span><button id="open" data-testid="open-segy" class="primary">Open SEG-Y</button><button id="correlate" data-testid="sweep-correlation">Sweep correlation</button><button id="convert" data-testid="convert-smartsolo">Convert SmartSolo</button><button id="map" data-testid="geometry-map">Geometry map / QC</button><button id="csv-headers" data-testid="header-csv">Export CSV</button><button id="csv-trace" data-testid="trace-csv">Trace CSV</button><button id="png" data-testid="plot-png">Export PNG</button><button id="legacy" title="Open the preserved v2.2 viewer">Legacy viewer</button><input id="files" data-testid="segy-file-input" type="file" accept=".sgy,.segy" multiple hidden><input id="smartsolo-files" data-testid="smartsolo-file-input" type="file" accept=".sgd,.segd" hidden></header><main class="layout"><aside class="panel" id="left"></aside><section class="workspace"><div class="canvas-wrap"><canvas id="wiggle" data-testid="seismic-plot" aria-label="Seismic wiggle display"></canvas><div class="drop" id="drop"><strong>Open local SEG-Y files</strong><span class="meta">Files remain in your browser. Large files are indexed through bounded Blob slices.</span><p><button id="open-drop" class="primary">Select files</button></p></div></div><div class="panel" id="flow"></div></section><aside class="panel right" id="right"></aside></main><footer class="status"><span id="status" role="status" aria-live="polite">Ready</span><span id="memory">Cache: 64 MiB per dataset</span><span id="diagnostics"></span><span id="local-runtime" data-testid="local-runtime" title="Local build and browser status">${this.escape(initialLocalRuntimeStatus())}</span></footer></div>`; this.renderer = new WiggleRenderer(this.byId<HTMLCanvasElement>("wiggle")); this.bind(); void this.render(); void this.updateLocalRuntimeStatus(); }
  private async updateLocalRuntimeStatus(): Promise<void> { const localServer = await localServerRuntimeStatus(); if (localServer) this.byId("local-runtime").textContent = `${initialLocalRuntimeStatus()} · ${localServer}`; }
  private bind(): void { const fileInput = this.byId<HTMLInputElement>("files"); const smartSoloInput = this.byId<HTMLInputElement>("smartsolo-files"); const select = () => fileInput.click(); this.byId("open").addEventListener("click", select); this.byId("open-drop").addEventListener("click", select); this.byId("correlate").addEventListener("click", () => this.openSweepCorrelation()); this.byId("convert").addEventListener("click", () => smartSoloInput.click()); this.byId("map").addEventListener("click", () => void this.openGeometryMap()); this.byId("csv-headers").addEventListener("click", () => this.openCsvDialog()); this.byId("csv-trace").addEventListener("click", () => this.openCsvDialog()); this.byId("png").addEventListener("click", () => this.openPngDialog()); this.byId("legacy").addEventListener("click", openLegacySegdViewer); fileInput.addEventListener("change", () => void this.openFiles(fileInput.files)); smartSoloInput.addEventListener("change", () => void this.openSmartSolo(smartSoloInput.files)); const drop = this.byId("drop"); document.addEventListener("dragover", (event) => { event.preventDefault(); drop.classList.remove("hidden"); }); document.addEventListener("drop", (event) => { event.preventDefault(); void this.openFiles(event.dataTransfer?.files ?? null); }); }
  private async openFiles(files: FileList | null): Promise<void> { if (!files?.length) return; const status = this.byId("status"); for (const file of Array.from(files)) { try { status.textContent = `Opening ${file.name}…`; this.addDataset(await SegyReader.open(file, { onProgress: (progress) => { status.textContent = progress.phase === "indexing" ? `Indexing ${file.name}: ${progress.traceCount} traces` : `Reading ${file.name} headers`; } })); } catch (error) { status.textContent = error instanceof Error ? error.message : String(error); } } this.fitTime(); await this.render(); }
  private active(): SegyDataset | undefined { return this.entries[this.activeIndex]?.dataset; }
  private fitTime(): void { const dataset = this.active(); if (!dataset || dataset.traceCount === 0) return; const ns = dataset.traceIndex.sampleCounts[0] ?? 1; const dt = (dataset.traceIndex.sampleIntervalsMicroseconds[0] ?? 1000) / 1_000_000; this.view = { ...this.view, timeStartSeconds: 0, timeEndSeconds: Math.max(dt, (ns - 1) * dt), firstTrace: 0 }; }
  private addDataset(dataset: SegyDataset): void { this.entries.push({ dataset }); this.activeIndex = this.entries.length - 1; this.selectedTrace = 0; }
  private async openSmartSolo(files: FileList | null): Promise<void> { const file = files?.[0]; if (!file) return; await new SmartSoloConversionDialog({ onConverted: async (dataset) => { this.addDataset(dataset); this.fitTime(); await this.render(); } }).open(file); }
  private openSweepCorrelation(): void { const dataset = this.active(); if (!dataset) { this.byId("status").textContent = "Open a SEG-Y dataset before selecting a sweep for correlation."; return; } new SweepCorrelationDialog({ dataset, onCorrelated: async (result) => { this.addDataset(result); this.fitTime(); await this.render(); } }).open(); }
  private async openGeometryMap(): Promise<void> { const dataset = this.active(); if (!dataset) return; try { await new GeometryMapPanel({ initialTraceId: this.selectedTrace, onSelectTrace: (traceId) => { this.selectedTrace = traceId; void this.render(); } }).open(dataset); } catch (error) { this.byId("status").textContent = error instanceof Error ? error.message : String(error); } }
  private openCsvDialog(): void { const dataset = this.active(); if (!dataset) return; new CsvExportDialog({ dataset, selectedTraceId: this.selectedTrace, visibleTraceIds: this.visibleTraceIds(dataset) }).open(); }
  private openPngDialog(): void { const dataset = this.active(); if (!dataset) return; new PngExportDialog({ dataset, view: this.view, visibleTraceIds: this.visibleTraceIds(dataset) }).open(); }
  private visibleTraceIds(dataset: SegyDataset): Uint32Array { const count = Math.max(0, Math.min(this.view.traceCount, dataset.traceCount - this.view.firstTrace)); return Uint32Array.from({ length: count }, (_, index) => this.view.firstTrace + index); }
  private async render(): Promise<void> { const dataset = this.active(); this.renderLeft(dataset); this.renderFlow(dataset); this.renderRight(dataset); this.byId("drop").classList.toggle("hidden", Boolean(dataset)); this.byId("dataset-chip").textContent = dataset ? `${dataset.name} · ${dataset.traceCount} traces` : "No local data loaded"; const canvas = this.byId<HTMLCanvasElement>("wiggle"); canvas.dataset.mode = this.view.mode; canvas.dataset.selectedTrace = String(this.selectedTrace); if (dataset && this.renderer) await this.renderer.render(dataset, this.view, this.selectedTrace); }
  private renderLeft(dataset: SegyDataset | undefined): void { const left = this.byId("left"); if (!dataset) { left.innerHTML = `<div class="section"><h2>Dataset</h2><p class="meta">Open SEG-Y revisions 0, 1, or 2. Textual/binary headers and trace samples are read lazily.</p></div>`; return; } left.innerHTML = `<div class="section"><h2>Datasets</h2><div class="file-list">${this.entries.map((entry, index) => `<button class="file-item ${index === this.activeIndex ? "active" : ""}" data-dataset="${index}">${this.escape(entry.dataset.name)}<br><span class="meta">${entry.dataset.traceCount} traces · ${entry.dataset.codec.name}</span></button>`).join("")}</div></div><div class="section"><h2>Display</h2><div class="controls"><label class="grid">Mode <select id="mode"><option value="wiggle">Wiggle</option><option value="variable-area">Variable area</option><option value="density">Density</option></select></label><label class="grid">Gain <input id="gain" type="number" min="0.01" step="0.1" value="${this.view.gain}"></label><label class="grid">Clip <input id="clip" type="number" min="0.1" step="0.1" value="${this.view.clip}"></label><label class="grid">First trace <input id="first" type="number" min="1" max="${dataset.traceCount}" value="${this.view.firstTrace + 1}"></label><label class="grid">Count <input id="count" type="number" min="1" max="${dataset.traceCount}" value="${this.view.traceCount}"></label></div></div><div class="section"><h2>Gather / sweep</h2><button id="run-sweep">Load sweep and run correlation…</button><button id="find-sweep">Inspect auxiliary sweep traces</button><p id="sweep-result" class="meta">Use a two-column time/amplitude file when the sweep interval is not 1 ms.</p></div>`; left.querySelectorAll<HTMLButtonElement>("[data-dataset]").forEach((button) => button.addEventListener("click", () => { this.activeIndex = Number(button.dataset.dataset); this.selectedTrace = 0; this.fitTime(); void this.render(); })); this.byId<HTMLSelectElement>("mode").value = this.view.mode; this.bindDisplayControls(); this.byId("run-sweep").addEventListener("click", () => this.openSweepCorrelation()); this.byId("find-sweep").addEventListener("click", () => void this.inspectSweep(dataset)); }
  private bindDisplayControls(): void { const update = () => { const dataset = this.active(); if (!dataset) return; this.view = { firstTrace: Math.max(0, Number(this.byId<HTMLInputElement>("first").value) - 1), traceCount: Math.max(1, Number(this.byId<HTMLInputElement>("count").value)), timeStartSeconds: this.view.timeStartSeconds, timeEndSeconds: this.view.timeEndSeconds, mode: this.byId<HTMLSelectElement>("mode").value as WiggleView["mode"], gain: Number(this.byId<HTMLInputElement>("gain").value), clip: Number(this.byId<HTMLInputElement>("clip").value) }; this.byId<HTMLCanvasElement>("wiggle").dataset.mode = this.view.mode; void this.renderer?.render(dataset, this.view, this.selectedTrace); }; ["mode", "gain", "clip", "first", "count"].forEach((id) => this.byId(id).addEventListener("input", update)); }
  private renderFlow(dataset: SegyDataset | undefined): void { this.byId("flow").innerHTML = `<div class="section"><h2>Processing flow</h2><div class="node-list"><div class="node">Source dataset <span class="meta">${dataset ? "lazy trace access" : "awaiting input"}</span></div><div class="node">Gain / AGC <span class="meta">available processor</span></div><div class="node">Filter / resample <span class="meta">available processor</span></div><div class="node">Sweep correlation <span class="meta">worker-backed</span></div><div class="node">Deconvolution <span class="meta">spiking / predictive API</span></div></div><p class="meta">Processing graphs are serializable; UI graph editing is intentionally conservative in this first modular pass.</p></div>`; }
  private renderRight(dataset: SegyDataset | undefined): void { const right = this.byId("right"); if (!dataset) { right.innerHTML = `<div class="section"><h2>Headers and QC</h2><p class="meta">Open a dataset to inspect raw and scaled SEG-Y metadata.</p></div>`; return; } const tabs: readonly RightTab[] = ["text", "binary", "trace", "qc"]; right.innerHTML = `<div class="tabs">${tabs.map((tab) => `<button class="tab ${tab === this.currentTab ? "active" : ""}" data-tab="${tab}">${tab}</button>`).join("")}</div><div id="tab-content" class="meta">Loading…</div>`; right.querySelectorAll<HTMLButtonElement>("[data-tab]").forEach((button) => button.addEventListener("click", () => { this.currentTab = button.dataset.tab as RightTab; this.renderRight(dataset); })); void this.renderTabContent(dataset); }
  private async renderTabContent(dataset: SegyDataset): Promise<void> { const content = this.byId("tab-content"); if (this.currentTab === "text") { content.innerHTML = `<pre>${this.escape(dataset.textualHeaders[0]?.cards().join("\n") ?? "")}</pre>`; return; } if (this.currentTab === "binary") { const values = dataset.binaryHeader.values; content.innerHTML = `<table>${Object.entries(values).map(([key, value]) => `<tr><td>${this.escape(key)}</td><td>${this.escape(String(value))}</td></tr>`).join("")}</table>`; return; } if (this.currentTab === "qc") { content.innerHTML = `${dataset.diagnostics.map((item) => `<p class="${item.severity === "warning" ? "warning" : item.severity === "error" ? "error" : ""}">${this.escape(item.message)}</p>`).join("") || "No parser warnings."}`; this.byId("diagnostics").textContent = `${dataset.diagnostics.length} diagnostics`; return; } const header = await dataset.traces.readHeader(this.selectedTrace); content.innerHTML = `<table>${TraceHeaderSchema.map((field) => `<tr><td>${this.escape(field.displayName)}</td><td>${this.escape(String(header.raw(field.id)))}</td><td>${this.escape(String(header.scaled(field.id)))}</td></tr>`).join("")}</table>`; }
  private async inspectSweep(dataset: SegyDataset): Promise<void> { const result = this.byId("sweep-result"); const candidates = SweepDetector.fromDataset(dataset); if (candidates.length === 0) { result.textContent = "No auxiliary trace candidate was found; select an external or generated sweep."; return; } const candidate = candidates[0]; if (!candidate) return; const sweep = await SweepExtractor.fromAuxiliaryTrace(dataset, candidate.traceId); const plan = CorrelationPlan.create(sweep, { output: "same", algorithm: "auto", removeTraceMean: true, removeSweepMean: true, sweepTaperFraction: 0, normalization: "sweep-energy" }); result.textContent = `Candidate trace ${candidate.traceId + 1}, score ${candidate.score}: ${candidate.reasons.join("; ")}. Correlation plan ready (${plan.constructor.name}).`; plan.dispose(); }
  private byId<T extends HTMLElement = HTMLElement>(id: string): T { const value = this.root.querySelector<T>(`#${id}`); if (!value) throw new Error(`Expected #${id} in the application shell.`); return value; }
  private escape(value: string): string { return value.replace(/[&<>"']/g, (character) => ({ "&": "&amp;", "<": "&lt;", ">": "&gt;", '"': "&quot;", "'": "&#39;" })[character] ?? character); }
}
