import type { TraceBlock } from "../../core/model/trace";
import { throwIfAborted } from "../../core/errors/errors";
import type { ProcessingContext, ProcessingInputMetadata, ResourceEstimate, SeismicProcessor, ValidationIssue } from "../api/processor";
export interface FilterParameters { readonly mode: "lowpass" | "highpass" | "bandpass" | "notch"; readonly lowFrequencyHz?: number; readonly highFrequencyHz?: number; readonly quality?: number; readonly zeroPhase?: boolean; }
interface Biquad { readonly b0: number; readonly b1: number; readonly b2: number; readonly a1: number; readonly a2: number; }
/** Second-order Butterworth-style filters; zero-phase mode applies forward/backward filtering. */
export class FilterProcessor implements SeismicProcessor<FilterParameters> {
  public readonly id = "filter"; public readonly version = "1.0.0"; public readonly displayName = "Frequency filter";
  public validate(input: ProcessingInputMetadata, parameters: FilterParameters): readonly ValidationIssue[] { const nyquist = 0.5 / input.sampleIntervalSeconds; const issues: ValidationIssue[] = []; const low = parameters.lowFrequencyHz ?? 0; const high = parameters.highFrequencyHz ?? nyquist * 0.9; if (low < 0 || high <= 0 || high >= nyquist) issues.push({ severity: "error", message: `Frequencies must be inside 0..${nyquist} Hz.` }); if (parameters.mode === "bandpass" && low >= high) issues.push({ severity: "error", message: "Band-pass low cutoff must be below high cutoff." }); return issues; }
  public estimateResources(input: ProcessingInputMetadata): ResourceEstimate { return { peakBytes: input.maximumSamplesPerTrace * 8, operations: input.traceCount * input.maximumSamplesPerTrace * 12, workerRecommended: input.traceCount > 64 }; }
  public async processBlock(block: TraceBlock, parameters: FilterParameters, context: ProcessingContext): Promise<TraceBlock> { const samples = block.samples.slice(); const stages = this.stages(parameters, block.sampleIntervalSeconds); for (let row = 0; row < block.traceIds.length; row += 1) { throwIfAborted(context.signal, "Filtering"); const start = block.sampleOffsets[row] ?? 0; const end = block.sampleOffsets[row + 1] ?? start; const trace = samples.subarray(start, end); for (const stage of stages) this.apply(trace, stage); if (parameters.zeroPhase ?? true) { trace.reverse(); for (const stage of stages) this.apply(trace, stage); trace.reverse(); } context.reportProgress(row + 1, block.traceIds.length); } await Promise.resolve(); return { ...block, samples }; }
  private stages(parameters: FilterParameters, dt: number): readonly Biquad[] { const nyquist = 0.5 / dt; const q = parameters.quality ?? Math.SQRT1_2; if (parameters.mode === "lowpass") return [this.biquad("lowpass", parameters.highFrequencyHz ?? nyquist * 0.9, q, dt)]; if (parameters.mode === "highpass") return [this.biquad("highpass", parameters.lowFrequencyHz ?? 1, q, dt)]; if (parameters.mode === "notch") return [this.biquad("notch", parameters.lowFrequencyHz ?? 50, q, dt)]; return [this.biquad("highpass", parameters.lowFrequencyHz ?? 1, q, dt), this.biquad("lowpass", parameters.highFrequencyHz ?? nyquist * 0.9, q, dt)]; }
  private biquad(kind: "lowpass" | "highpass" | "notch", frequency: number, quality: number, dt: number): Biquad { const omega = 2 * Math.PI * frequency * dt; const alpha = Math.sin(omega) / (2 * quality); const cosine = Math.cos(omega); let b0 = 0; let b1 = 0; let b2 = 0; const a0 = 1 + alpha; const a1 = -2 * cosine; const a2 = 1 - alpha; if (kind === "lowpass") { b0 = (1 - cosine) / 2; b1 = 1 - cosine; b2 = b0; } else if (kind === "highpass") { b0 = (1 + cosine) / 2; b1 = -(1 + cosine); b2 = b0; } else { b0 = 1; b1 = -2 * cosine; b2 = 1; } return { b0: b0 / a0, b1: b1 / a0, b2: b2 / a0, a1: a1 / a0, a2: a2 / a0 }; }
  private apply(trace: Float32Array, coefficients: Biquad): void { let x1 = 0; let x2 = 0; let y1 = 0; let y2 = 0; for (let index = 0; index < trace.length; index += 1) { const x = trace[index] ?? 0; const y = coefficients.b0 * x + coefficients.b1 * x1 + coefficients.b2 * x2 - coefficients.a1 * y1 - coefficients.a2 * y2; trace[index] = y; x2 = x1; x1 = x; y2 = y1; y1 = y; } }
}
