import { describe, expect, it } from "vitest";
import { ibm32ToNumber, numberToIbm32 } from "../../src/io/segy/codecs/ibm-float";
import { defaultSampleCodecRegistry } from "../../src/io/segy/codecs/sample-codec-registry";

describe("SEG-Y sample codecs", () => {
  it("round trips IBM positive, negative, and zero values", () => { for (const value of [0, 1, -1, 16, -0.125, 1234.5]) expect(ibm32ToNumber(numberToIbm32(value))).toBeCloseTo(value, 5); });
  it("decodes documented IBM hexadecimal byte patterns", () => { expect(ibm32ToNumber(0x41100000)).toBe(1); expect(ibm32ToNumber(0xc1100000)).toBe(-1); expect(ibm32ToNumber(0)).toBe(0); expect(ibm32ToNumber(0x41100000)).toBeCloseTo(1); });
  it("decodes signed and unsigned 24-bit limits", () => { const signed = defaultSampleCodecRegistry.get(7); const unsigned = defaultSampleCodecRegistry.get(15); const bytes = new ArrayBuffer(6); const view = new DataView(bytes); view.setUint8(0, 0x7f); view.setUint8(1, 0xff); view.setUint8(2, 0xff); view.setUint8(3, 0x80); view.setUint8(4, 0); view.setUint8(5, 0); const destination = new Float32Array(2); signed.decode(view, 0, 2, false, destination); expect([...destination]).toEqual([8_388_607, -8_388_608]); unsigned.decode(view, 0, 1, false, destination); expect(destination[0] ?? 0).toBe(8_388_607); });
  it("honours IEEE endianness", () => { const codec = defaultSampleCodecRegistry.get(5); const bytes = new ArrayBuffer(4); new DataView(bytes).setFloat32(0, 2.5, true); const destination = new Float32Array(1); codec.decode(new DataView(bytes), 0, 1, true, destination); expect(destination[0]).toBe(2.5); });
  it("honours non-standard little-endian IBM words", () => { const codec = defaultSampleCodecRegistry.get(1); const bytes = new ArrayBuffer(4); new DataView(bytes).setUint32(0, numberToIbm32(-2), true); const destination = new Float32Array(1); codec.decode(new DataView(bytes), 0, 1, true, destination); expect(destination[0]).toBe(-2); });
  it("encodes and decodes 24-bit values in little endian order", () => { const signed = defaultSampleCodecRegistry.get(7); const unsigned = defaultSampleCodecRegistry.get(15); const source = new Float32Array([-8_388_608, 8_388_607]); const bytes = new ArrayBuffer(6); signed.encode?.(source, 0, 2, new DataView(bytes), 0, true); const destination = new Float32Array(2); signed.decode(new DataView(bytes), 0, 2, true, destination); expect(destination).toEqual(source); const unsignedBytes = new ArrayBuffer(3); unsigned.encode?.(new Float32Array([16_777_215]), 0, 1, new DataView(unsignedBytes), 0, true); unsigned.decode(new DataView(unsignedBytes), 0, 1, true, destination); expect(destination[0]).toBe(16_777_215); });
  it("rejects 64-bit integer samples that lose exact JavaScript integer precision", () => { const codec = defaultSampleCodecRegistry.get(9); const bytes = new ArrayBuffer(8); new DataView(bytes).setBigInt64(0, 9_007_199_254_740_992n, false); expect(() => codec.decode(new DataView(bytes), 0, 1, false, new Float32Array(1))).toThrow(/safely/i); });
  it("refuses unsupported fixed-point-with-gain format", () => expect(() => defaultSampleCodecRegistry.get(4)).toThrow(/requires/i));
});
