import { describe, expect, it } from "vitest";
import { convolve } from "../../src/processing/vibroseis/convolution";
import { deconvolve, levinsonDurbin, solveToeplitz } from "../../src/processing/vibroseis/deconvolution";

describe("convolution and deconvolution", () => {
  it("matches direct and FFT convolution", () => { const signal = new Float32Array([1, 2, 3, 4, 5, 6, 7]); const kernel = new Float32Array([1, -0.5, 0.25]); const fft = convolve(signal, kernel, "full", "fft"); const direct = convolve(signal, kernel, "full", "direct"); for (let index = 0; index < direct.length; index += 1) expect(fft[index] ?? 0).toBeCloseTo(direct[index] ?? 0, 5); });
  it("solves a stable Toeplitz system", () => { const result = levinsonDurbin(new Float64Array([2, 0.5, 0.1]), 2); expect(result[0] ?? 0).toBe(1); expect([...result].every(Number.isFinite)).toBe(true); });
  it("solves general predictive Toeplitz right-hand sides", () => { const result = solveToeplitz(new Float64Array([2, 0.5]), new Float64Array([1, -1])); expect(result[0]).toBeCloseTo(2 / 3, 8); expect(result[1]).toBeCloseTo(-2 / 3, 8); });
  it("returns a spiking operator and rejects invalid lengths", () => { const trace = new Float32Array(64); trace[8] = 1; trace[24] = 0.6; const result = deconvolve(trace, { operatorLengthSamples: 8, predictionDistanceSamples: 0, prewhiteningFraction: 0.01 }); expect(result.operator).toHaveLength(9); expect(result.samples).toHaveLength(trace.length); expect(() => deconvolve(trace, { operatorLengthSamples: 64, predictionDistanceSamples: 0, prewhiteningFraction: 0 })).toThrow(); });
  it("suppresses a predictable periodic multiple without changing the causal time origin", () => { const trace = new Float32Array(512); for (let index = 0; index < trace.length; index += 1) trace[index] = Math.sin(2 * Math.PI * index / 16); const result = deconvolve(trace, { operatorLengthSamples: 8, predictionDistanceSamples: 1, prewhiteningFraction: 0.01 }); let inputEnergy = 0; let outputEnergy = 0; for (let index = 64; index < trace.length; index += 1) { inputEnergy += (trace[index] ?? 0) ** 2; outputEnergy += (result.samples[index] ?? 0) ** 2; } expect(outputEnergy).toBeLessThan(inputEnergy * 0.2); expect(result.samples[0]).toBeCloseTo(trace[0] ?? 0, 6); });
  it("rejects singular prewhitening and invalid design windows", () => { const zeros = new Float32Array(32); expect(() => deconvolve(zeros, { operatorLengthSamples: 4, predictionDistanceSamples: 0, prewhiteningFraction: 0 })).toThrow(/singular/i); expect(() => deconvolve(new Float32Array(32), { operatorLengthSamples: 4, predictionDistanceSamples: 0, designStartSample: 10, designEndSampleExclusive: 12, prewhiteningFraction: 0.1 })).toThrow(/window/i); });
});
