import type { TraceBlock } from "../../core/model/trace";
import { throwIfAborted } from "../../core/errors/errors";
import type { ProcessingContext, ProcessingInputMetadata, ResourceEstimate, SeismicProcessor, ValidationIssue } from "../api/processor";
export interface NoiseParameters { readonly mode: "demean" | "detrend" | "median-despike"; readonly threshold?: number; }
export class NoiseProcessor implements SeismicProcessor<NoiseParameters> {
  public readonly id = "noise"; public readonly version = "1.0.0"; public readonly displayName = "Basic noise attenuation";
  public validate(_input: ProcessingInputMetadata, parameters: NoiseParameters): readonly ValidationIssue[] { return parameters.mode === "median-despike" && !((parameters.threshold ?? 0) > 0) ? [{ severity: "error", field: "threshold", message: "Despike threshold must be positive." }] : []; }
  public estimateResources(input: ProcessingInputMetadata): ResourceEstimate { return { peakBytes: input.maximumSamplesPerTrace * 8, operations: input.traceCount * input.maximumSamplesPerTrace * 8, workerRecommended: input.traceCount > 32 }; }
  public async processBlock(block: TraceBlock, parameters: NoiseParameters, context: ProcessingContext): Promise<TraceBlock> { const samples = block.samples.slice(); for (let row = 0; row < block.traceIds.length; row += 1) { throwIfAborted(context.signal, "Noise attenuation"); const start = block.sampleOffsets[row] ?? 0; const end = block.sampleOffsets[row + 1] ?? start; const trace = samples.subarray(start, end); if (parameters.mode === "demean") this.demean(trace); else if (parameters.mode === "detrend") this.detrend(trace); else this.despike(trace, parameters.threshold ?? 6); context.reportProgress(row + 1, block.traceIds.length); } return { ...block, samples }; }
  private demean(trace: Float32Array): void { let sum = 0; for (let index = 0; index < trace.length; index += 1) sum += trace[index] ?? 0; const mean = sum / Math.max(1, trace.length); for (let index = 0; index < trace.length; index += 1) trace[index] = (trace[index] ?? 0) - mean; }
  private detrend(trace: Float32Array): void { let sx = 0; let sy = 0; let sxx = 0; let sxy = 0; for (let index = 0; index < trace.length; index += 1) { const value = trace[index] ?? 0; sx += index; sy += value; sxx += index * index; sxy += index * value; } const d = trace.length * sxx - sx * sx; const slope = d === 0 ? 0 : (trace.length * sxy - sx * sy) / d; const intercept = (sy - slope * sx) / Math.max(1, trace.length); for (let index = 0; index < trace.length; index += 1) trace[index] = (trace[index] ?? 0) - intercept - slope * index; }
  private despike(trace: Float32Array, threshold: number): void { if (trace.length < 3) return; for (let index = 1; index < trace.length - 1; index += 1) { const a = trace[index - 1] ?? 0; const b = trace[index] ?? 0; const c = trace[index + 1] ?? 0; const median = [a, b, c].sort((left, right) => left - right)[1] ?? b; const deviation = Math.abs(b - median); const local = Math.abs(a - c) + Number.EPSILON; if (deviation > threshold * local) trace[index] = median; } }
}
